runtime: go116

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
# Reference: https://chromium.googlesource.com/infra/luci/luci-go/+/HEAD/examples/appengine/helloworld_v2/app.yaml
luci_gae_vars:
  chops-gofindit-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    OAUTH_CLIENT_ID: 68570714943-khbhofqbfrtppep12vc0n33viee97o2i.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://chops-gofindit-dev.appspot.com/auth/openid/callback
    TINK_AEAD_KEY: sm://tink-aead-primary
  chops-gofindit:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com
    OAUTH_CLIENT_ID: 662477201230-59qlg57msier1po1dshpt3r21g4hlrq7.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://chops-gofindit.appspot.com/auth/openid/callback
    TINK_AEAD_KEY: sm://tink-aead-primary

handlers:
- url: /.*
  script: auto
  secure: always

# Pubsub Handler.
- url: /_ah/push-handlers/.*
  script: auto
  secure: always

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -encrypted-cookies-client-id ${OAUTH_CLIENT_ID}
  -encrypted-cookies-client-secret ${OAUTH_CLIENT_SECRET}
  -encrypted-cookies-redirect-url ${OAUTH_REDIRECT_URL}
  -encrypted-cookies-tink-aead-key ${TINK_AEAD_KEY}
  -frontend-client-id ${OAUTH_CLIENT_ID}
