runtime: go116
service: default

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
# Reference: https://chromium.googlesource.com/infra/luci/luci-go/+/HEAD/examples/appengine/helloworld_v2/app.yaml
#
# This configuration is only used for developer testing. The
# configuration used for development and production instances is
# contained in the infradata/gae repo. Refer to LUCI GAE Automatic
# Deployment for more (go/luci/how_to_deploy.md) (Googlers only).
luci_gae_vars:
  poros-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    OAUTH_CLIENT_ID: 364968137392-nlqfkvsi5vt8egtp1u75r6j6k3lken7c.apps.googleusercontent.com
    OAUTH_CLIENT_SECRET: sm://oauth-client-secret
    OAUTH_REDIRECT_URL: https://poros-dev.appspot.com/auth/openid/callback
    ROOT_SECRET: sm://root-secret
    TINK_AEAD_KEY: sm://tink-aead-primary

handlers:
- url: /prpc/.*
  secure: always
  script: auto

- url: /(.*\.(png|css|js|txt|json))$
  static_files: static/\1
  upload: static/(.*)

- url: /.*
  script: auto
  secure: always


entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -encrypted-cookies-client-id ${OAUTH_CLIENT_ID}
  -frontend-client-id ${OAUTH_CLIENT_ID}
  -encrypted-cookies-client-secret ${OAUTH_CLIENT_SECRET}
  -encrypted-cookies-redirect-url ${OAUTH_REDIRECT_URL}
  -encrypted-cookies-tink-aead-key ${TINK_AEAD_KEY}
  -root-secret ${ROOT_SECRET}
